### ISSUE TITLE
Percentual de conclusão da meta

### ISSUE THREAD

**Issue by adrianora** [marianaalucena/dev-web#2]
Seria interessante além da meta, ter um mecanismo que permitisse mensurar qual a sua situação atual, transparecendo se a meta está próxima ou distante. Ainda nessa linha, além da data fim, seria bacana também armazenar a data que a meta teve início.

**Comment by marianaalucena** [comment]
Adriano, pensei em colocar esse percentual de conclusão como extra, caso sobre tempo ao final do projeto. Creio que com a funcionalidade (extra) de adicionar tasks a meta será mais fácil acompanhar a evolução das mesmas. Inclui a adição da data de início da meta.
