### ISSUE TITLE
Mudar retorno de rota "/metas"

### ISSUE THREAD

**Issue by DiegoGamaV** [marianaalucena/dev-web#3]
A rota `/metas` no momento retorna o JSON com a mensagem "Usuário criado!", como abaixo, ao invés de "Meta criada!".
```json
{
	"message": "Usuário criado!"
}
```
Talvez fosse mais útil retornar o objeto que acabou de ser criado, com o id. Isso vai possibilitar já armazenar o id no frontend quando você for implementar o componente de cadastro de meta, porque já vai ter o ID dele ao invés de ter de fazer uma segunda chamada apenas para isso.

**Comment by marianaalucena** [comment]
Feito!!
